config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
  }
  scope module: :user do
    root 'homes#top'
  end
  namespace :admin do
    # get '/' => '/'
    resources :users,only: [:index,:show,:edit,:update,:destroy
    ]
    resources :genres,only: [:index,:create,:edit,:update,:destroy]
    resources :tags,only: [:index,:show,:edit,:update]
    resources :sanctuarys, only: [:index, :show, :destroy] do
      resources :sanctuary_comments, only: [:destroy]
    end

    end
# ユーザー用
# URL /customers/sign_in ...
  devise_for :user,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

get 'search', to: 'searches#search'

 namespace :user do
  #root to: 'homes#top'
  get 'homes/about'
  resources :sanctuarys, only: [:new, :create, :index, :show,:edit, :destroy,:collection] do
    resources :sanctuary_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :impression, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :update]
  get 'quit', to: 'users#quit'
  patch 'out', to: 'users#out'

 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sanctuary.rb
class Sanctuary < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  # has_many :impressions, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :sanctuary_comments, dependent: :destroy
  has_many :sanctuary_tags, dependent: :destroy
  belongs_to :genre


  # dependent: :destroyでPostが削除されると同時にPostとTagの関係が削除される
  has_many :sanctuary_tags, dependent: :destroy

  # throughを利用して、tag_mapsを通してtagsとの関連付け(中間テーブル)
  #   Post.tagsとすれば、Postに紐付けられたTagの取得が可能
  has_many :tags, through: :sanctuary_tags

  def get_image(width,height)
    unless image.attached?
     file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
     image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

   def favorited_by?(user)
    favorites.exists?(user_id: user.id)
   end

  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :place, presence: true
  validates :impression, presence: true

def save_tags(tags)

    # タグをスペース区切りで分割し配列にする
    #   連続した空白も対応するので、最後の“+”がポイント
    tag_list = tags.split(/[[:blank:]]+/)

    # 自分自身に関連づいたタグを取得する
    current_tags = self.tags.pluck(:name)

    # (1) 元々自分に紐付いていたタグと投稿されたタグの差分を抽出
    #   -- 記事更新時に削除されたタグ
    old_tags = current_tags - tag_list

    # (2) 投稿されたタグと元々自分に紐付いていたタグの差分を抽出
    #   -- 新規に追加されたタグ
    new_tags = tag_list - current_tags

    # tag_mapsテーブルから、(1)のタグを削除
    #   tagsテーブルから該当のタグを探し出して削除する
    old_tags.each do |old|
      # tag_mapsテーブルにあるpost_idとtag_idを削除
      #   後続のfind_byでtag_idを検索
      self.tags.delete Tag.find_by(name: old)
    end

    # tagsテーブルから(2)のタグを探して、tag_mapsテーブルにtag_idを追加する
    new_tags.each do |new|
      # 条件のレコードを初めの1件を取得し1件もなければ作成する
      # find_or_create_by : https://railsdoc.com/page/find_or_create_by
      new_post_tag = Tag.find_or_create_by(name: new)

      # tag_mapsテーブルにpost_idとtag_idを保存
      #   配列追加のようにレコードを渡すことで新規レコード作成が可能
      self.tags << new_post_tag
    end

  end

  def self.search(keyword)
    genre = Genre.where('genre_name LIKE ?', "%#{keyword}%")

    # あいまい検索
    #   “?”に対してkeywordが順番に入る
    #   LIKEは、あいまい検索の意味で、“%”は、前後のあいまいという意味
    #   “#{keyword}”は、Rubyの式展開
    #   .orで、ジャンルを追加検索している
    #   ref: https://style.potepan.com/articles/29804.html
    where('name LIKE ? OR place LIKE ? OR impression LIKE ?', "%#{keyword}%", "%#{keyword}%", "%#{keyword}%").or(where(genre_id: genre.ids))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :sanctuarys, dependent: :destroy
  has_many :impressions, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :sanctuary_comments, dependent: :destroy

 def active_for_authentication?
    super && (is_deleted == false)
 end

  def get_image(width,heigth)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, heigth]).processed
  end

  validates :name, presence: true
end

app/controllers/admin/sanctuarys_controller.rb
class Admin::SanctuarysController < ApplicationController

  def index
    @sanctuarys = Sanctuary.all
  end

  def show
    @sanctuary = Sanctuary.find(params[:id])
  end

  def destroy
    sanctuary = Sanctuary.find(params[:id])  # データ（レコード）を1件取得
    sanctuary.destroy  # データ（レコード）を削除
    redirect_to admin_sanctuarys_path # 聖地一覧画面へリダイレクト
  end

  private

  def sanctuary_params
    params.require(:sanctuary).permit(:image,:name,:user_id,:genre_id,:sanctuary_tags_id,:favorite_id,:place,:impression,:longitude,:latitude)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
    @user= User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
		  flash[:success] = "ユーザー情報を更新しました"
			redirect_to admin_user_path(@user)
		else
			render "edit"
		end
  end

  private
  def user_params
	  params.require(:user).permit(:name,:introduction,:sns,:email,:is_deleted)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.new(sanctuary_id: params[:sanctuary_id])
    favorite.save
    redirect_to user_sanctuary_path(params[:sanctuary_id])
  end

  def destroy
    favorite = current_user.favorites.find_by(sanctuary_id: params[:sanctuary_id])
    favorite.destroy
    redirect_to user_sanctuary_path(params[:sanctuary_id])
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
 before_action :configure_sign_up_params, only: [:create]

  def after_sign_up_path_for(resource)
    root_path(resource)
  end
  # before_action :configure_account_update_params, only: [:update]

  # # GET /resource/sign_up
  # def new
  # end

  # # POST /resource
  # def create
  # end

  # # GET /resource/edit
  # # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/user/sanctuary_comments_controller.rb
class User::SanctuaryCommentsController < ApplicationController
  def create
    @sanctuary_comment = SanctuaryComment.new(sanctuary_params)
    @sanctuary_comment.save
    redirect_to user_sanctuary_path(params[:sanctuary_id])
  end

  def destroy
    SanctuaryComment.find(params[:id]).destroy
    redirect_to user_sanctuary_path(params[:sanctuary_id])
  end

  private

  def sanctuary_params
    params.require(:sanctuary_comment).permit(:comment)
          .merge(user_id: current_user.id, sanctuary_id: params[:sanctuary_id])
  end
end

app/controllers/user/sanctuarys_controller.rb
class User::SanctuarysController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def new
    @sanctuary =Sanctuary.new
  end

  def create
    @sanctuary = Sanctuary.new(sanctuary_params)
    @sanctuary.user_id = current_user.id
    if @sanctuary.save
      @sanctuary.save_tags(params[:sanctuary][:tag_name])
      flash[:success] = "聖地を登録しました"
      redirect_to user_sanctuarys_path
    else
      render :new
    end
  end

  def index
    @sanctuarys = Sanctuary.all.page(params[:page])
    @sanctuary = Sanctuary.new
    @images = Sanctuary.all
  end

  def show
    @sanctuary = Sanctuary.find(params[:id])
    @sanctuary_comment = SanctuaryComment.new
    @sanctuary_comments = SanctuaryComment.where(sanctuary_id: params[:id])
  end

  def edit
    @sanctuary = Sanctuary.find(params[:id])
  end

  def update
     @sanctuary = Sanctuary.find(params[:id])
    if @sanctuary.update(sanctuary_params)
      flash[:notice] ="聖地を更新しました"
      redirect_to user_sanctuary_path(@sanctuary)
    else
      render "show"
    end
  end

  def destroy
    sanctuary = Sanctuary.find(params[:id])  # データ（レコード）を1件取得
    sanctuary.destroy  # データ（レコード）を削除
    redirect_to 'show'  # 投稿一覧画面へリダイレクト
  end

  def search
    @results = @q.result
  end

private

  def set_q
    @q = Sanctuary.ransack(params[:q])
  end

  def sanctuary_params
    params.require(:sanctuary).permit(
      :name,
      :favorite_id,
      :genre_id,
      :user_id,
      :longitude,
      :latitude,
      :place,
      :impression,
      :address,
      images: []
      )
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  protected
   # 退会しているかを判断するメソッド
  def user_state
  ## 【処理内容1】 入力されたemailからアカウントを1件取得
  @user = User.find_by(email: params[:user][:email])
  ## アカウントを取得できなかった場合、このメソッドを終了する
  return if !@user
  ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
  if @user.valid_password?(params[:user][:password]) && (@user.is_deleted ==false)
    flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
    redirect_to new_user_registration_path
    ## 【処理内容3】「1」と「2」の処理が真(true)だった場合、そのアカウントのis_deletedカラムに格納されている値を確認し
      # trueだった場合、退会しているのでサインアップ画面に遷移する
  else
      flash[:notice] = "項目を入力してください"
      # falseだった場合、
    # true && false == false
  end
  end
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      flash[:success] = "登録情報を変更しました"
      redirect_to user_user_path
    else
      render :edit and return
    end
  end

  def quit
  end

  def out
    @user = current_user
    @user.update(is_deleted: true)

    reset_session
    flash[:notice] = "ありがとうございました。またご利用ください。"
    redirect_to root_path
  end

  def user_params
  	params.require(:user).permit(:name, :email, :favorite_id,:sanctuary_id,:sns,:introduction,:is_deleted,:image)
  end
end

app/helpers/admin/sanctuarys_helper.rb
module Admin::SanctuarysHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/sanctuary_comments_helper.rb
module User::SanctuaryCommentsHelper
end

app/views/user/sanctuarys/edit.html.erb
<h1>User::Sanctuarys#edit</h1>
<p>Find me in app/views/user/sanctuarys/edit.html.erb</p>

app/views/user/sanctuarys/new.html.erb
    <h2 class="head-line title_h2 text-center">聖地登録</h2>





<%= form_with(model: @sanctuary, url: user_sanctuarys_path, method: :post, class: "form-horizontal") do |f| %>
  <div class="row">
    <div class="col-md-6">
      <% if @sanctuary.errors.any? %>
        <%= @sanctuary.errors.count %>件のエラーが発生しました
        <ul>
          <% @sanctuary.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <h4>聖地名</h4>
        <%= f.text_field :name %>
      <h4>ジャンル</h4>
      <%#= f.select :genre_id, [['ヨーロッパ・アメリカ', 1], ['アフリカ', 2], ['アジア・オセアニア', 3]] %>
      <%= f.collection_select(:genre_id, Genre.all, :id, :genre_name) %>
      <h4>タグ</h4>
      <%= f.text_field :tag_name %>
      <h4>感想</h4>
        <%= f.text_area :impression %>
      <h4>画像</h4>
        <%= f.file_field :images, accept: "image/*", multiple: true %>
      <%= f.submit '登録する', class: "btn btn-success" %>
    </div>
    <div class="col-md-6">
      <%= f.text_field :place, placeholder: '富士山' %>
      <input type="button" value="検索" onclick="codeAddress()">
      <p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
      <div id="map"></div>
    </div>
  </div>
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
<% end %>

<style>
  #map {
    width: 100%;
    height: 400px;
  }
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 8,

  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('sanctuary_place').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	// ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('sanctuary_latitude').value = results[0].geometry.location.lat();
        document.getElementById('sanctuary_longitude').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('sanctuary_latitude').value = ev.latLng.lat();
            document.getElementById('sanctuary_longitude').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });
}

</script>


<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

app/views/user/sanctuarys/show.html.erb
<div class="container">
  <h2>聖地詳細</h2>
  <div id="map"></div>

  <% if @sanctuary.images.attached? %>
    <div class="row my-3">
      <% @sanctuary.images.each do |image| %>
        <div class="col-md-4">
          <div class="card">
            <%= image_tag image, class: 'img-fluid', style: 'width: 100%; height: 200px; object-fit: cover;' %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      聖地名
      <h3><%= @sanctuary.name %></h3>
    </div>
    <div class="col-md-4">
      ジャンル
      <h5><%= @sanctuary.genre.genre_name %></h3>
    </div>
    <div class="col-md-4">
      感想
      <div><%= simple_format(@sanctuary.impression) %></div>
    </div>
  </div>
  <div>
    <% @sanctuary.tags.each do |tag| %>
      <span class="badge rounded-pill bg-warning text-dark p-2"><%= tag.name %></span>
    <% end %>
  </div>
 <% if @sanctuary.favorited_by?(current_user) %>
    <p>
      <%= link_to user_sanctuary_favorites_path(@sanctuary), method: :delete do %>
        ♥<%= @sanctuary.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to  user_sanctuary_favorites_path(@sanctuary), method: :post do %>
        ♡<%= @sanctuary.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
  <hr>

  <%= form_with model: @sanctuary_comment, url: user_sanctuary_sanctuary_comments_path(@sanctuary), method: :post do |f| %>

    <%= f.label :comment, 'コメント :' %>
    <%= f.text_area :comment, class: 'form-control' %>

    <div class="row">
      <div class="col-12 col-md-3 mx-auto">
        <%= f.submit '登録する', class: "btn btn-success btn-block my-3" %>
      </div>
    </div>

  <% end %>

  <% @sanctuary.sanctuary_comments.each do |s_comment| %>
    <div>
      <h6><%= s_comment.user.name %></h6>
      <%= simple_format(s_comment.comment) %>
      <% if s_comment.user_id == current_user.id %>
        <%= link_to '🗑', user_sanctuary_sanctuary_comment_path(@sanctuary, s_comment), method: :delete, data: {confirm: '削除しますか？'} %>
      <% end %>
    </div>
  <% end %>

</div>

<style>
  #map {
    width: 100%;
    height: 200px;
  }
</style>

<script>
  function initMap(){
    let map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: <%= @sanctuary.latitude ||= 0 %>, lng: <%= @sanctuary.longitude ||= 0 %> },
    zoom: 15
    });

  marker = new google.maps.Marker({
    // コントローラーで定義した変数から緯度経度を呼び出し、マーカーを立てる
    position: {
      lat: <%= @sanctuary.latitude %>,
      lng: <%= @sanctuary.longitude %>
    },
    map: map
  });
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>